# Generated by Django 5.1.1 on 2024-09-23 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlapp', '0003_remove_modelinfo_confusion_matrix_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelinfo',
            name='cm_false_negative',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelinfo',
            name='cm_false_positive',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelinfo',
            name='cm_true_negative',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelinfo',
            name='cm_true_positive',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
