# Generated by Django 5.1.1 on 2024-09-23 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelinfo',
            name='confusion_matrix_image',
            field=models.ImageField(blank=True, null=True, upload_to='confusion_matrices/'),
        ),
    ]
